spring:
  application:
    name: fix-acceptor1

fix:
  enabled: true
  settings:
    external-file: acceptor.cfg
    classpath-fallback: fix/acceptor.cfg
  runtime:
    cleanup-on-startup: true
    diagnostics-enabled: true
