spring:
  application:
    name: fix-acceptor1

fix:
  acceptor:
    enabled: true
    connection-type: acceptor
    file-store-path: fix-runtime/store
    file-log-path: fix-runtime/log
    start-time: 00:00:00
    end-time: 23:59:59
    use-data-dictionary: N
    sessions:
      - port: 9878
        begin-string: FIX.4.4
        sender-comp-id: ACCEPTOR
        target-comp-id: INITIATOR1
        heartbeat-interval-seconds: 30
        symbol: DEMO
        quantity: 100
        side: BUY
      - port: 9878
        begin-string: FIX.4.4
        sender-comp-id: ACCEPTOR
        target-comp-id: INITIATOR2
        heartbeat-interval-seconds: 30
        symbol: DEMO
        quantity: 100
        side: SELL
